name: "FTP Mirror"
description: "Deploy files via FTP mirror"

inputs:
  server:
    required: true
  username:
    required: true
  password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run FTP mirror
      shell: pwsh
      run: |
        $script = "${{ github.action_path }}/ftp-mirror.ps1"

        & $script `
          -FtpServer "${{ inputs.server }}" `
          -FtpUser "${{ inputs.username }}" `
          -FtpPass "${{ inputs.password }}"